"""Alembic migration environment configured for async SQLAlchemy.

This environment connects Alembic to the application's *existing*
declarative :class:`Base` metadata (``app.db.session.Base``) so that
autogenerated migrations always reflect the true ORM schema.

Key points:

* All model modules are imported here (``users``, ``objectives``,
  ``roadmap_days``, ``system_prompts``) so their ``Base``-inheriting
  tables/enums are registered on the metadata before autogenerate runs.
* The connection URL is NOT hardcoded: it is read from
  ``app.core.config.get_settings().database_url`` (which honours the
  ``DATABASE_URL`` environment variable / ``.env`` file), matching the
  URL used by the application's async engine in ``app.db.session``.
* The environment uses Alembic's ``async_engine_from_config`` support so
  migrations run against the same ``postgresql+asyncpg`` URL the app uses.
"""

import asyncio
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# Ensure the project root (where the ``app`` package lives) is on the
# import path so ``env.py`` can import the application's settings and
# models regardless of which directory the ``alembic`` CLI is invoked
# from.
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# The ``app`` imports below intentionally follow the ``sys.path``
# bootstrap above; ``noqa: E402`` marks them as needed.
from app import models  # noqa: E402,F401  (registers all model tables on ``Base.metadata``)
from app.core.config import get_settings  # noqa: E402
from app.db.session import Base  # noqa: E402
from app.models import (  # noqa: E402,F401
    objective,
    roadmap_day,
    system_prompt,
    user,
)

# Alembic Config object, which provides access to the values within the
# .ini file in use.
config = context.config

# Interpret the config file for Python logging.  This line sets up
# loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Apply the application's resolved database URL (from env / .env) so the
# migration run targets the same database as the running app.  Overriding
# here keeps the migrations stack in sync with the async engine used by
# the API.
config.set_main_option(
    "sqlalchemy.url",
    get_settings().database_url,
)

# Set the target metadata to the app's declarative base metadata.  This
# is what alembic compares against when generating migrations.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine,
    though an Engine is acceptable here as well.  By skipping the Engine
    creation we don't even need a DBAPI to be available.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations against an async engine created from the config URL.

    The engine mirrors the application's own async engine (same
    ``DATABASE_URL``).  ``poolclass=pool.NullPool`` ensures no pooling
    layer interferes with the short-lived migration process.
    """
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (over an actual engine)."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
