"""
Model package — imports every ORM model so that ``Base.metadata`` is
fully populated.

Importing this package (or ``from app import models``) registers all
tables and native enums on :class:`app.db.session.Base.metadata`.  Both
the application and the Alembic ``env.py`` rely on this to enumerate the
full schema for autogenerated migrations.
"""

from app.models.objective import Objective
from app.models.roadmap_day import RoadmapDay, RoadmapDayStatus
from app.models.system_prompt import SystemPrompt
from app.models.user import User, UserRole

__all__ = [
    "Objective",
    "RoadmapDay",
    "RoadmapDayStatus",
    "SystemPrompt",
    "User",
    "UserRole",
]
